"""
Type hints for the Cython MIDI module.
These stubs provide proper type information for IDE support and mypy.
"""

from typing import Tuple

import numpy as np

def get_event_times(midi_events: np.ndarray, tempo_events: np.ndarray, ticks_per_quarter: int) -> np.ndarray: ...
def read_var_length_cython(data: bytes, offset: int) -> Tuple[int, int]: ...
def unpack_uint32_cython(data: bytes) -> int: ...
def unpack_uint8_pair_cython(data: bytes) -> Tuple[int, int]: ...
def unpack_uint16_triplet_cython(data: bytes) -> Tuple[int, int, int]: ...
def decode_pitch_bend_cython(data: bytes) -> int: ...
def encode_pitchbend_cython(value: int) -> Tuple[int, int]: ...
def _parse_midi_track_cython(data: bytes, offset: int) -> Tuple[int, np.ndarray, bytes, list]: ...
def _encode_midi_track_cython(name: bytes, events: np.ndarray) -> np.ndarray: ...
