# copied from https://docs.pypi.org/trusted-publishers/using-a-publisher/
name: Upload Python Package

on:
  release:
    types: [published]
    
permissions:
  contents: read
  id-token: write
  
jobs:
  # Add a job to run tests directly before allowing publish
  verify-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      python-version: '["3.11"]'  # Run with a single version to be faster
  
  pypi-publish:
    name: upload release to PyPI
    needs: verify-tests  # This makes publish job wait for verify-tests to succeed
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Ensure tag matches pyproject.toml version
        run: |
          TAG_VERSION=${GITHUB_REF##*/}
          PYPROJECT_VERSION=$(grep -Po '(?<=^version = ")[^"]*' pyproject.toml)
          if [ "$TAG_VERSION" != "$PYPROJECT_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match pyproject.toml version ($PYPROJECT_VERSION)"
            exit 1
          fi

      - name: Build source distribution from src
        run: python -m build --sdist --outdir dist    
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
